import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-64 flex flex-col items-center justify-end">
        <h1 className="text-3xl text-blue-700 font-bold">Home Page</h1>
        <div className="mt-4 flex gap-4 font-semibold">
          <Link href="/Login">
            <h1 className="hover:text-blue-600 cursor-pointer">Log In</h1>
          </Link>
          <Link href="/Signup">
            <h1 className="hover:text-blue-600 cursor-pointer">Sign Up</h1>
          </Link>
          <Link href="/user/Dashboard">
            <h1 className="hover:text-blue-600 cursor-pointer">
              User Dashboard
            </h1>
          </Link>
        </div>
      </div>
    </div>
  );
}
